version: 1
disable_existing_loggers: false

formatters:
  rich_default:
    format: "%(message)s"
    datefmt: "[%X]"

  rich_task:
    format: "Node '%(daglite_node_key)s' - %(message)s"
    datefmt: "[%X]"

  file_detailed:
    format: "%(asctime)s | %(levelname)-8s | %(name)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  rich_console:
    class: rich.logging.RichHandler
    level: INFO
    formatter: rich_default
    rich_tracebacks: true
    tracebacks_show_locals: false
    show_time: true
    show_level: true
    show_path: true
    markup: true

  rich_console_task:
    class: rich.logging.RichHandler
    level: INFO
    formatter: rich_task
    rich_tracebacks: true
    tracebacks_show_locals: false
    show_time: true
    show_level: true
    show_path: false
    markup: true

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: file_detailed
    filename: run.log
    mode: w
    encoding: utf-8

loggers:
  daglite:
    level: DEBUG
    handlers: [rich_console, file]
    propagate: false

  daglite.lifecycle:
    level: DEBUG
    handlers: [rich_console, file]
    propagate: false

  daglite.tasks:
    level: DEBUG
    handlers: [rich_console_task, file]
    propagate: false

root:
  level: WARNING
  handlers: [rich_console]
