coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 5%  # Allows coverage to drop to 90% (95% - 5%)
    patch:
      default:
        target: 70%

comment:
  layout: "reach, diff, files"
  behavior: default