coverage:
  status:
    project:
      default:
        target: 90%  # TODO: set to 100% for 1.0 release
        threshold: 1%  # Allow 1% drop from target
    patch:
      default:
        target: 80%  # TODO: set to 100% for 1.0 release
        threshold: 1%  # Allow 1% drop from target

comment:
  require_changes: false
  require_base: false
  require_head: true
